name: gh-pages

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm i -g npm-check-updates
          ncu
          npm install
          npm run build-gh-pages

      - name: npm-check-updates
        run: |
          ncu

      - name: npm-check-updates2
        run: ncu

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
